### ISSUE TITLE
Recheck readme example after MLJ.jl update

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJFlow.jl#12]
In the pending PR #10, the example does `using MLJBase, MLJModels`, and so forth. After we rollout the new version of MLJ that will include `using MLJFlow` we can simplify the example to do `using MLJ` and so forth.

**Comment by ablaom** [comment]
? We haven't rolled out changes to MLJ.jl yet. We first need the new MLJBase.jl release, and then add `using MLJFlow` to MLJ/src/MLJ.jl`.

**Comment by ablaom** [comment]
I suggest reverting the readme example so that it actually works with the current MLJFlow#dev and your MLJBase PR.

**Comment by ablaom** [comment]
Also, I suggest you state in the example "Requires MLJ.jl version 0.19.3 or higher."

**Comment by pebeto** [comment]
Now on dev. Waiting until the next release to move it to master.
