### ISSUE TITLE
Duplicate run names intentional?

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJFlow.jl#16]
When I tried out the example and repeated the evaluation to generate new runs, they all had the same name. Is that intentional?

<img width="1105" alt="Screen Shot 2023-08-17 at 3 11 59 PM" src="https://github.com/JuliaAI/MLJFlow.jl/assets/30517088/11cfc15c-c5de-4c0a-8021-f2c46175b6a4">

**Comment by pebeto** [comment]
Yes, it is intentional because it was programmed to give you a hint of what kind of model belongs to that run. However, if it's needed, we can remove that naming and allow `mlflow` to generate a random name (not related to anything about the run).

**Comment by ablaom** [comment]
Okay, I'm assuming there's nothing the user could want to do that actually requires them to identify a run by name, and so this acceptable.  It Just seems a bit weird for run names to be duplicated. Generally, I think of "names" as synonymous with identifiers. Better would be "DecisionTreeClassifier 1", "DecisionTreeClassifier 2", and so forth, but I'm assuming that's a lot more complicated to implement, because you need a counter, and so forth. 

What if we let MLflow generate it's random names and add the model type name as a tag instead?
