### ISSUE TITLE
Issue to trigger releases

### ISSUE THREAD

**Issue by pebeto** [JuliaAI/MLJFlow.jl#19]

**Comment by pebeto** [comment]
@JuliaRegistrator register

**Comment by pebeto** [comment]
@JuliaRegistrator register

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Address breaking changes caused by migration of measure MLJBase.jl -> StatisticalMeasures.jl (#21)
- Make the string representations of metrics on the MLflow service more informative. The value of the first parameter of the metric is now included in the representation (#21)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

(**breaking**) Rename `MLFlowLogger` (exported) to `Logger` (unexported). So a logger instance is now instantiated with `using MLJFlow; logger = MLJFlow.Logger(baseuri)`.

(**testing**) Facilitate local testing by adding `MLFLOW_URI` environment variable to set the location of the running MLflow service (#30)

**Comment by pebeto** [comment]
@JuliaRegistrator register branch=master

Release notes:

(breaking) Removing `healthcheck` function on `Logger()` instantiation due to platforms inconsistency (see #34).

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

**Comment by pebeto** [comment]
@JuliaRegistrator register branch=master

**Comment by pebeto** [comment]
@JuliaRegistrator register branch=master

**Comment by pebeto** [comment]
@JuliaRegistrator register branch=master

Release notes:

- **[new feature]** Added complete support with MLJ's `TunedModel`, being fully-compatible with accelerators (`CPUThreads()` and `CPUProcesses()`). This feature is not supported by `mlflow`, but implemented here following a `Producer-Consumer` pattern using a `Channel` approach.
- **[fix]** `Logger` is now a mutable struct, which means that its fields are modifiable outside instantiation.

**Comment by pebeto** [comment]
@JuliaRegistrator register branch=master

Release notes:
- **[breaking]** Renaming `_logging_channel` to `logging_channel`, and changing its type from `Channel{Tuple}` to `Union{Channel{Tuple}, Nothing}`
- **[breaking]** `open_logging_channel` function now requires a `Logger` instance and doesn't return a `Channel` anymore. The reason is to keep `logging_channel` in a "private" form in our model
- **[improvement]** Removed non-useful `wait!(result_channel)` in `src/base.jl`
- **[improvement]** Explicitly closing the `logging_channel` when a result is retrieved in the background worker

**Comment by pebeto** [comment]
@JuliaRegistrator register branch=master

Release notes:

- **[breaking]** Updated all `MLFlowClient.jl` API calls to match the latest version: `createrun` now takes a `String` experiment ID, `updaterun` takes status as a keyword with `RunStatus` enum, `logparam` requires `String` arguments, and `searchruns` is keyword-only with experiment_ids
- **[breaking]** Replaced `logartifact` with `uploadartifact` via the mlflow-artifacts proxy, as the old run-scoped artifact upload no longer exists in `MLFlowClient.jl`
- **[breaking]** `save` now returns the `Run` object explicitly instead of the `RunInfo` returned by `updaterun`
- **[improvement]** Added `MLJFlow.load(logger, run)` helper to download and deserialize a saved machine artifact from a run
- **[improvement]** Added `getorcreateexperiment` helper since it was removed from `MLFlowClient.jl`. Handles active, deleted, and non-existent experiments via create-first-then-fallback with automatic restore
- **[improvement]** Background worker in `open_logging_channel` now catches exceptions and propagates them back through the result channel instead of silently dying and causing infinite hangs
- **[improvement]** `log_evaluation` result channel changed from `Channel{Run}` to `Channel{Any}` to support error propagation via `CapturedException`

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Bump compatibility requirement for MLJFlowClient.jl to 0.9 to enable use of MLJFlow.jl with mlflow 3.11.1 and higher (#59)

**Comment by ablaom** [comment]
Oops. I need to merge dev onto master first.

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Bump compatibility requirement for MLJFlowClient.jl to 0.9 to enable use of MLJFlow.jl with mlflow 3.11.1 and higher (#59)

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master
