### ISSUE TITLE
Add accessor method to extract the "client" from an `MLFlowLogger object`

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJFlow.jl#8]
As discussed on a call.

I know we have been calling this `client` but I wonder if this is really the correct word, since it is on a server most (all?) of the time. I see that MLFlowClient.jl documentation calls an instance of `MLFlow` an "MLFlow API service", so maybe "service" is a better work for this.

**Comment by pebeto** [comment]
You're completely right. `service` is a better naming for this kind of instance.
